Title: Jane Onyi
logo: https://raw.githubusercontent.com/janeonyi/Portofolio/bd4fbbd520e0730acd3cd7677548021917f6a6f7/folder_name/profile%20pict2.png?raw=true
#show_downloads: true
theme: jekyll-theme-minimal
